version: "3.9"
services:
  consumer:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    environment:
      DB_LINK: postgresql+asyncpg://postgresql:postgresql@postgresql:5432/postgresql
      SECRET_KEY: AS;DKFJLH197H8FYOIutyo&tyouyp(8UY%&^())
      MINIO_ACCESS_KEY: NCitCJJY49q8ZY4YiLP4
      MINIO_SECRET_KEY: GdUd3KB6KJOEAP7YStpJmAO9QFX9C25EId2XXn5C
      S3_URL: s3.labofdev.ru
      S3_BUCKET_NAME: test-bucket
      ALGORITHM: HS256
      ELASTICSEARCH_URL: https://elastic.labofdev.ru:443
      KAFKA_LINK: kafka-1:9092
    networks:
      - web

networks:
  web:
    external: true
