"""init

Revision ID: 2bf54dc44061
Revises: 
Create Date: 2024-11-30 12:38:45.682974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf54dc44061'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_product',
    sa.Column('credit_product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('max_loan_amount', sa.Float(), nullable=True),
    sa.Column('min_repayment_term', sa.Integer(), nullable=True),
    sa.Column('collateral_required', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('credit_product_id', 'id'),
    sa.UniqueConstraint('credit_product_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transaction_type',
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_name', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_type_id', 'id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transaction_type_id')
    )
    op.create_table('credit_agreement',
    sa.Column('credit_agreement_id', sa.Integer(), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.Column('loan_term', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('credit_product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['credit_product_id'], ['credit_product.credit_product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credit_agreement_id', 'customer_id', 'credit_product_id', 'id'),
    sa.UniqueConstraint('credit_agreement_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('credit_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_amount', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('credit_agreement_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['credit_agreement_id'], ['credit_agreement.credit_agreement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_type.transaction_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'customer_id', 'credit_agreement_id', 'transaction_type_id', 'id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_transaction')
    op.drop_table('credit_agreement')
    op.drop_table('transaction_type')
    op.drop_table('customer')
    op.drop_table('credit_product')
    # ### end Alembic commands ###
