"""fix_fact

Revision ID: 2bf8daedcc3c
Revises: ceb4139ec1be
Create Date: 2024-11-30 17:26:24.730644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf8daedcc3c'
down_revision: Union[str, None] = 'ceb4139ec1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fact', ['contract_id'])
    op.create_unique_constraint(None, 'fact', ['contract_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact', type_='unique')
    op.drop_constraint(None, 'fact', type_='unique')
    # ### end Alembic commands ###
