"""add_fact

Revision ID: 7623eafc6547
Revises: 2bf54dc44061
Create Date: 2024-11-30 17:08:37.058436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7623eafc6547'
down_revision: Union[str, None] = '2bf54dc44061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('credit_sum', sa.Float(), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('made_payments', sa.Integer(), nullable=True),
    sa.Column('calculated_payment_number', sa.Float(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('contract_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['credit_agreement.credit_agreement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credit_sum', 'contract_id', 'user_id', 'id'),
    sa.UniqueConstraint('credit_sum'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact')
    # ### end Alembic commands ###
