"""fix_fact

Revision ID: aae4acc0da76
Revises: 2bf8daedcc3c
Create Date: 2024-11-30 18:10:21.901897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae4acc0da76'
down_revision: Union[str, None] = '2bf8daedcc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('fact', sa.Column('user_tin', sa.String(), nullable=True))
    op.add_column('fact', sa.Column('user_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'user_phone')
    op.drop_column('fact', 'user_tin')
    op.drop_column('fact', 'user_name')
    # ### end Alembic commands ###
